-- SQLense - 数据库实验课
-- ============================
-- 学生: ${STUDENT_NAME}
-- 任务: 创建学生表
--
-- 连接到数据库:
--   psql -h $PG_HOST -U $PG_USER -d $PG_DATABASE
--
-- 提示:
--   1. 使用 lab 模式: SET search_path TO lab;
--   2. 创建 students 表
--   3. 执行 \dt lab.* 查看表
--   4. 执行 \d lab.students 查看表结构
