name: base
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - fastapi
    - uvicorn
    - pydantic
    - httpx
    - python-dotenv
    - asyncpg
    - pydantic-ai-slim
    - openai
    - pymupdf
